spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     password: '{cipher}AQAnTgUGTyIcaM77c1tZKQH+lhwyuK6OigP73Wh1B0QjU6kN2FsrCMaKKldl/x9ddOucw5AnCk6MeSxj4amx8S/ZAIVhtdiZOgewb5yCR7/NQkUEw/SycwqQ2T5qvqucNz2b3JatW56Q1568rZbibH6R7+fbC8LxVKNZcvIrxyT/DPtw8t3BkvSOdpRvgRd5QvdVn8OUJUhHbigsjTZla3VEIQwjCDe0aD0XzVRY69fAzIleQrQtCv9Bwla6J8EAhXh4+kQy+q8H4Uxm7sd3ISAaVi32vcn70OXfseAsq9ib+gl/Jm7NyaEnL3tiZHhrJwk8Ys3im2PtLuojhGpHNo908qnHA6QNr3JHTc29j1MR1OJ6jr8BPE/DzAcuFw0myD8='
     url: '{cipher}AQCbtmzesubb+VFsxt1C49JDrZ3+erzg3nnE0vgCjn6KQKAH49yWFxX1XTE9DEFr+qMBm+mwCEtYb5go/40/A9WdnM9nH09+M18ICjurr0XRoPprPRjzmWZ/2q78ZJ92mTIhj8thMJwq4wxwM1mcsx29GAGqU+YLYpT1aPwf/GVkbKUWUc57+QdWqehz18aVIiuNKZ359MTErAlKrjKJoY9vrK54mSJFzjkyl/j/qbYsQrupZ7J4Sy/WniZ0oXDdgJMoiRd5NzRvgXCAUTN9eReQmWpMmI2d3qF+37uXq3bQ+AoGCudmNfZMimg+5VGvqO5fu+jA6NzeCfLRn9QnSm7uXFwlXdm9RZrGIN6sBNZlDdcBPG0UC9mKs/wENAprFTpBesBCr6/oRXv4KaVh7Q2Ky7nXlTueuo2mcebr5MzN8/n2FrMUmfr34vSOe/ql6AMqWSVDy508pIHXfFMUrOskP+1IGqSgGpenzeBOhpxkLg=='
     username: '{cipher}AQCYQWxTaDrMFiyjTSsvOJi5RKPlU39ocOujcEnfU3bnoHl6v06p88XoSlugMqV1SrRqC5LoyVPKfDFnkJQK/DgCHUfFGWNIIYb1NPP6TLXZV0j1OIFO+6XRXleEZ2kQHzS30i7IEwHf+YHcvNpL9kmUn30qHirAuijkANKGkrKa4xBjxmdKENNGDaLh45og9CT4k7t2V+12S0CxWcW5AmblljZAM/n5XxsAt7HLOBljwjsfZWm07uP3LnHftRFRRhNWVDz4zIBkYsGgKopRTUM7gRZTjpVC2VXolEIADtcxuC/RgJuf0I/sL9VZlm58Y4jnXarRDkevJtyBFJWiJGn7UVOQHVXKNH2QmkQY9KF4o583/slZk6xjYgGJId2aCAA='
  swagger:
    enabled: true
    title: 接口文档
    description: 接口信息
    version: 1.0.0
    contact:
      name: zws
      email: 2848392861@qq.com
    security:
       username: zws
       password: '{cipher}AQA+zeyJTXQId3Ac57Rh+iNNP3YfqMGKf95DoB7miDqMpC7FBikFfbJFdmOJf8eQ0/Ldc0PG6VoRexVkgNfCf3gDTv59ce89k7N49JKsR3ekgGAx22SIgZi06YYlYhDe4fZtcfY4Qaud+5KdLRF9nK2UI54FHKI295KAjv4HIcbJ6nI5GXKfykHziaoEj6fv7o77pWAa9bK2hBBcqOAlVNlHVPAsPQcZIPmpYIeaz3En2fls8qr3YwO0q7M0JmbwMwsFePCqTOhdHOlD7tIfAiHveow+5QPjGRL3bEaYCGo7VREkmSMidZc9SDd/gPCcrYZSerbZeEBajVVBxSBXQlMtYHyyDRtwv6cNWbqiUP+5sJ/HD/QXyJYxo48eLlkDMBk='
       filter-plugin: true
    global-response-messages:
       POST[0]:
          code: 400
          message: 请求参数错误
       POST[1]:
          code: 404
          message: 页面未找到
       POST[2]:
          code: 401
          message: 页面未授权   
    #global-operation-parameters:
     #   -   description: 'Token信息,必填项'
      #      modelRef: 'string'
       #     name: 'Authorization'
        #    parameter-type: 'header'
         #   required: true
    base-package: com.zws
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false    
