spring:
  application:
    name: order
  cloud:
    config:
      discovery:
        service-id: config
        enabled: true
      profile: dev
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ # 多个以逗号隔开，eureka即是服务端，也是客户端
management:
  endpoints:
    web:
      exposure:
        include: '*'
test: bb2
